<?xml version="1.0" encoding="UTF-8"?>
<root>
  <queryResults name="Query1" value="Select ACCOUNT_ID, NAME, STATUS, TYPE, DATEOPENED, DATECLOSED From ACCOUNT">
    <failureMessage>CompareResults Error: Got expected exception but with wrong message. Got column "name" not found; sql statement:
select account_id, name, status, type, dateopened, dateclosed from account [42122-124]</failureMessage>
    <actualException>
      <exceptionType>JdbcSQLException</exceptionType>
      <message>Column "NAME" not found; SQL statement:
Select ACCOUNT_ID, NAME, STATUS, TYPE, DATEOPENED, DATECLOSED From ACCOUNT [42122-124]</message>
      <class>org.h2.jdbc.JdbcSQLException</class>
      <stackTrace>org.h2.jdbc.JdbcSQLException: Column "NAME" not found; SQL statement:
Select ACCOUNT_ID, NAME, STATUS, TYPE, DATEOPENED, DATECLOSED From ACCOUNT [42122-124]
	at org.h2.message.Message.getSQLException(Message.java:111)
	at org.h2.message.Message.getSQLException(Message.java:122)
	at org.h2.message.Message.getSQLException(Message.java:75)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:128)
	at org.h2.command.dml.Select.prepare(Select.java:715)
	at org.h2.command.Parser.prepareCommand(Parser.java:236)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1053)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:158)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:147)
	at org.jboss.bqt.framework.AbstractQuery.execute(AbstractQuery.java:208)
	at org.jboss.bqt.client.testcase.ProcessResults.executeTest(ProcessResults.java:215)
	at org.jboss.bqt.client.testcase.ProcessResults.runTestCase(ProcessResults.java:114)
	at org.jboss.bqt.client.TestClient.runScenario(TestClient.java:195)
	at org.jboss.bqt.client.TestClient.runTest(TestClient.java:130)
	at org.jboss.bqt.test.TestIntegrationWithLocalDB.testBQTClientExecutionResultSetModeCompareNo(TestIntegrationWithLocalDB.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</stackTrace>
    </actualException>
    <expectedException>
      <exceptionType>JdbcSQLException</exceptionType>
      <message>Table "NONEXISTING" not found; SQL statement:
Select ACCOUNT_ID, NAME, STATUS, TYPE, DATEOPENED, DATECLOSED From NONEXISTING [42102-124]</message>
      <class>org.h2.jdbc.JdbcSQLException</class>
    </expectedException>
  </queryResults>
</root>

